.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "VISAGE\-APP" "5" "September 2012" "" ""
.
.SH "NAME"
\fBvisage\-app\fR \- Run a standalone instance of Visage
.
.SH "SYNOPSIS"
\fBvisage\-app\fR \fIstart|genapache\fR
.
.SH "DESCRIPTION"
Visage is a web interface for viewing collectd statistics\.
.
.P
It also provides a JSON interface onto collectd\'s RRD data, giving you an easy way to mash up the data\.
.
.SH "OPTIONS"
.
.TP
\fBstart\fR
Start visage on \fB127\.0\.0\.1:9292\fR
.
.TP
\fBgenapache\fR
Generate a vhost suitable for Passenger + Apache\. Will load Visage from the installed gem\.
.
.SH "ENVIRONMENT"
.
.TP
\fBCONFIG_PATH\fR
Where to look for configuration files\. Added to the beginning of config load path, so files found in here take precedence over shipped config files\.
.
.TP
\fBRRDDIR\fR
Where to look for collectd\'s RRDs\. Must correspond with collectd\'s \fBrrdtool\fR plugin\'s \fBDataDir\fR value\.
.
.SH "AUTHOR"
Lindsay Holmwood \fIlindsay@holmwood\.id\.au\fR
.
.SH "COPYRIGHT"
MIT Licensed\.
