# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{visage-app}
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lindsay Holmwood"]
  s.date = %q{2011-02-15}
  s.default_executable = %q{visage-app}
  s.description = %q{Visage is a web interface for viewing collectd statistics. It also provides a JSON interface onto collectd's RRD data, giving you an easy way to mash up the data.}
  s.email = %q{lindsay@holmwood.id.au}
  s.executables = ["visage-app"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "Gemfile",
    "LICENCE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/visage-app",
    "features/builder.feature",
    "features/cli.feature",
    "features/data/config/with_no_profiles/.stub",
    "features/json.feature",
    "features/profiles.feature",
    "features/step_definitions/form_steps.rb",
    "features/step_definitions/json_steps.rb",
    "features/step_definitions/result_steps.rb",
    "features/step_definitions/site_steps.rb",
    "features/step_definitions/visage_steps.rb",
    "features/step_definitions/webrat_steps.rb",
    "features/support/env.rb",
    "lib/visage-app.rb",
    "lib/visage-app/collectd/json.rb",
    "lib/visage-app/collectd/profile.rb",
    "lib/visage-app/collectd/rrds.rb",
    "lib/visage-app/config.rb",
    "lib/visage-app/config.ru",
    "lib/visage-app/config/file.rb",
    "lib/visage-app/graph.rb",
    "lib/visage-app/helpers.rb",
    "lib/visage-app/patches.rb",
    "lib/visage-app/profile.rb",
    "lib/visage-app/public/favicon.gif",
    "lib/visage-app/public/images/active.png",
    "lib/visage-app/public/images/add.png",
    "lib/visage-app/public/images/hosts.png",
    "lib/visage-app/public/images/loader.gif",
    "lib/visage-app/public/images/metrics.png",
    "lib/visage-app/public/images/search.png",
    "lib/visage-app/public/javascripts/graph.js",
    "lib/visage-app/public/javascripts/highcharts.js",
    "lib/visage-app/public/javascripts/highcharts.src.js",
    "lib/visage-app/public/javascripts/keyboard.js",
    "lib/visage-app/public/javascripts/mootools-1.2.3-core.js",
    "lib/visage-app/public/javascripts/mootools-1.2.5.1-more.js",
    "lib/visage-app/public/stylesheets/screen.css",
    "lib/visage-app/views/builder.haml",
    "lib/visage-app/views/layout.haml",
    "lib/visage-app/views/profile.haml",
    "lib/visage-app/views/profiles.haml",
    "man/visage-app.5",
    "man/visage-app.5.ronn",
    "visage-app.gemspec"
  ]
  s.homepage = %q{http://visage-app.com/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{a web (interface | service) for viewing collectd statistics}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<tilt>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<errand>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_development_dependency(%q<shotgun>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<webrat>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, ["= 1.0"])
      s.add_runtime_dependency(%q<tilt>, ["= 1.0.1"])
      s.add_runtime_dependency(%q<haml>, ["= 3.0.13"])
      s.add_runtime_dependency(%q<errand>, ["= 0.7.2"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["= 0.7.6"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<tilt>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<errand>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<shotgun>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sinatra>, ["= 1.0"])
      s.add_dependency(%q<tilt>, ["= 1.0.1"])
      s.add_dependency(%q<haml>, ["= 3.0.13"])
      s.add_dependency(%q<errand>, ["= 0.7.2"])
      s.add_dependency(%q<yajl-ruby>, ["= 0.7.6"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<tilt>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<errand>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<shotgun>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sinatra>, ["= 1.0"])
    s.add_dependency(%q<tilt>, ["= 1.0.1"])
    s.add_dependency(%q<haml>, ["= 3.0.13"])
    s.add_dependency(%q<errand>, ["= 0.7.2"])
    s.add_dependency(%q<yajl-ruby>, ["= 0.7.6"])
  end
end

